"""empty message

Revision ID: 2b9673268493
Revises: 5d28e8dc7868
Create Date: 2023-06-22 14:47:11.979642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9673268493'
down_revision = '5d28e8dc7868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('account_account_id_key', type_='unique')

    with op.batch_alter_table('account_activity', schema=None) as batch_op:
        batch_op.drop_constraint('account_activity_activity_id_key', type_='unique')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_constraint('branch_branch_id_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_user_id_key', ['user_id'])

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.create_unique_constraint('branch_branch_id_key', ['branch_id'])

    with op.batch_alter_table('account_activity', schema=None) as batch_op:
        batch_op.create_unique_constraint('account_activity_activity_id_key', ['activity_id'])

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint('account_account_id_key', ['account_id'])

    # ### end Alembic commands ###
