"""empty message

Revision ID: 5d28e8dc7868
Revises: bd09554da014
Create Date: 2023-06-22 13:39:18.385921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d28e8dc7868'
down_revision = 'bd09554da014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('account_activity', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###
