"""empty message

Revision ID: dfdf05adbd1d
Revises: 4e43c66f7d16
Create Date: 2023-06-26 20:24:56.690096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdf05adbd1d'
down_revision = '4e43c66f7d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ever_dormant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('ever_dormant')

    # ### end Alembic commands ###
